### ISSUE TITLE
Create teoSim for Windows

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-configuration-files#4]
Create `teoSim` for Windows: `teoSim.bat` or similar. :-)

**Comment by PeterBowman** [comment]
OpenRAVE + WIndows = the unfulfilled roboticist's dream.

**Comment by jgvictores** [comment]
> OpenRAVE + WIndows = the unfulfilled roboticist's dream.

Used to be easy. I'd call it Paradise Lost. ^^

**Comment by PeterBowman** [comment]
I really think this is not feasible, we need to fix compilation of OpenRAVE on Windows (not attempted since many years) before even thinking about a `teoSim.bat`. This issue will remain open for ♾️+1.

**Comment by jgvictores** [comment]
I guess here are some options, I'm fine with either:
a. label `upstream` project column `waiting for third party`
b. label `wontfix`, close

**Comment by PeterBowman** [comment]
>  a. label `upstream` project column `waiting for third party`

We could wait forever. I'd say I'm OK if there is at least one relevant upstream issue in place, but it turns there already are some: https://github.com/rdiankov/openrave/issues/491, https://github.com/rdiankov/openrave/issues/371, https://github.com/rdiankov/openrave/issues/390, https://github.com/rdiankov/openrave/issues/391... Seems this topic has been dead for years, not addressed despite several people demanding a solution.

>  b. label `wontfix`, close

Definitely `willfix` as soon as we can, but it doesn't depend on us. I vote for `closed due to inactivity`. Yes, we have more of those, but this one is blocked until several planets align properly.

**Comment by jgvictores** [comment]
Okay! `closed due to inactivity` it is!
